name: Transport

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@vmw'
      - run: npm install
      - run: npm login
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
