name: Transport Release pipeline

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@vmw'
      - run: npm install --legacy-peer-deps
      - run: npm run pre-publish
      - uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: dist
  publish:
    runs-on: ubuntu-20.04
    needs:
      - build
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@vmw'
      - run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: dist/
      - run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
